updated example
/** @jsx React.DOM */ causes an error on startup:
SyntaxError: C:/Users/code/hapi-react/views/index.jsx: Line 1: The @jsx React.DOM pragma has been deprecated as of React 0.12